- key:               xgame
  name:              Xgamecoin 
  client:            xgamecoin                             # API client name.
  server:            http://user:password@127.0.0.1:35465    # Public Xgamecoin node endpoint.
  height:            1087160                                 # Initial block number from which sync will be started.
  min_confirmations: 6                                       # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://xgamecoin.tk/blockexplorer/index.php?address=#{address}
    transaction:     https://xgamecoin.tk/blockexplorer/index.php?transaction=#{txid}
  status:            active
